# Generated by Django 3.0.1 on 2020-01-08 10:33

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Başlık')),
                ('img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('auth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Yazar')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Diğer Adlar')),
                ('type', models.TextField(blank=True, null=True, verbose_name='Novel Tipi')),
                ('genre', models.TextField(blank=True, null=True, verbose_name='Novel Türü')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='Etiket')),
                ('league', models.TextField(blank=True, null=True, verbose_name='Orjinal Dil')),
                ('year', models.TextField(blank=True, null=True, verbose_name='Yayınlanma Tarihi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Konu')),
                ('publishing_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('slug', models.SlugField(editable=False, max_length=510)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=250, verbose_name='Bölüm İsmi')),
                ('chapter_number', models.CharField(max_length=250, verbose_name='Bölüm Numarası')),
                ('cevirmen', models.CharField(blank=True, max_length=50, null=True, verbose_name='Çevirmen')),
                ('redaktor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Redaktör')),
                ('chapter_content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('slug', models.SlugField(editable=False, max_length=510, unique=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Bölümler', to='novel.Novel')),
            ],
            options={
                'ordering': ['-created_date', 'id'],
            },
        ),
    ]
