# Generated by Django 3.0.1 on 2020-01-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Novel Türü'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='league',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Orjinal Dil'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Diğer Adlar'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Etiket'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Novel Tipi'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Yayınlanma Tarihi'),
        ),
    ]
