# Generated by Django 3.0.1 on 2020-01-09 11:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20200109_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nc_name', models.CharField(max_length=150, verbose_name='İsminiz')),
                ('nc_content', ckeditor.fields.RichTextField(verbose_name='Yorumunuz')),
                ('nc_created_date', models.DateTimeField(auto_now_add=True)),
                ('nc_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novelcomment', to='novel.Novel')),
            ],
        ),
        migrations.CreateModel(
            name='ChapterComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_name', models.CharField(max_length=150, verbose_name='İsminiz')),
                ('cc_content', ckeditor.fields.RichTextField(verbose_name='Yorumunuz')),
                ('cc_created_date', models.DateTimeField(auto_now_add=True)),
                ('cc_novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptercomment', to='novel.Chapter')),
            ],
        ),
    ]
