# Generated by Django 3.0.1 on 2020-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_chaptercomment_novelcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptercomment',
            name='cc_content',
            field=models.TextField(verbose_name='Yorumunuz'),
        ),
        migrations.AlterField(
            model_name='novelcomment',
            name='nc_content',
            field=models.TextField(verbose_name='Yorumunuz'),
        ),
    ]
