# Generated by Django 3.0.1 on 2020-01-10 15:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novel', '0004_auto_20200109_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=200, verbose_name='Blog Başlık')),
                ('b_img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('b_content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('b_created_date', models.DateTimeField(auto_now_add=True)),
                ('b_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Duyurular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_title', models.CharField(max_length=50, verbose_name='Duyuru Başlığı')),
                ('d_content', models.CharField(max_length=200, verbose_name='İçerik')),
                ('d_created_date', models.DateTimeField(auto_now_add=True)),
                ('d_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_title', models.CharField(max_length=200, verbose_name='Forum Başlığı')),
                ('f_content', models.CharField(max_length=500, verbose_name='İçerik')),
                ('f_created_date', models.DateTimeField(auto_now_add=True)),
                ('f_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='Haberler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('h_img', models.FileField(blank=True, null=True, upload_to='', verbose_name='Resim')),
                ('h_content', ckeditor.fields.RichTextField(verbose_name='İçerik')),
                ('h_created_date', models.DateTimeField(auto_now_add=True)),
                ('h_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
        ),
        migrations.CreateModel(
            name='HaberlerComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_name', models.CharField(max_length=20, verbose_name='Adınız')),
                ('hc_content', models.CharField(max_length=150, verbose_name='Yorumunuz')),
                ('hc_created_date', models.DateTimeField(auto_now_add=True)),
                ('hc_haberler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haberlercomment', to='novel.Haberler')),
            ],
        ),
        migrations.CreateModel(
            name='ForumComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fc_name', models.CharField(max_length=150, verbose_name='İsminiz')),
                ('fc_content', models.CharField(max_length=150, verbose_name='Yorumunuz')),
                ('fc_created_date', models.DateTimeField(auto_now_add=True)),
                ('fc_forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forumcomment', to='novel.Forum')),
            ],
        ),
        migrations.CreateModel(
            name='DuyurularComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(max_length=20, verbose_name='Adınız')),
                ('dc_content', models.CharField(max_length=150, verbose_name='Yorumunuz')),
                ('dc_created_date', models.DateTimeField(auto_now_add=True)),
                ('dc_haberler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duyurularcomment', to='novel.Duyurular')),
            ],
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_name', models.CharField(max_length=20, verbose_name='Adınız')),
                ('bc_content', models.CharField(max_length=150, verbose_name='Yorumunuz')),
                ('bc_created_date', models.DateTimeField(auto_now_add=True)),
                ('bc_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogcomment', to='novel.Blog')),
            ],
        ),
    ]
