# Generated by Django 3.0.1 on 2020-01-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0005_blog_blogcomment_duyurular_duyurularcomment_forum_forumcomment_haberler_haberlercomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='bc_blog',
        ),
        migrations.RemoveField(
            model_name='duyurularcomment',
            name='dc_haberler',
        ),
        migrations.RemoveField(
            model_name='forum',
            name='f_user',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='fc_forum',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='DuyurularComment',
        ),
        migrations.DeleteModel(
            name='Forum',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
    ]
