# Generated by Django 3.0.1 on 2020-01-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0006_auto_20200110_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haberler',
            options={'ordering': ['-h_created_date']},
        ),
        migrations.DeleteModel(
            name='Duyurular',
        ),
    ]
